### ISSUE TITLE
FMOD bank files come out garbled upon extraction (RtMI)

### ISSUE THREAD

**Issue by modusc896d352** [fzipp/gg#4] opened 2022-09-27 03:50 UTC
so, i tested out the latest [ggpack](https://pkg.go.dev/github.com/fzipp/gg/cmd/ggpack) version with the new ggpack format from RtMI and though i managed to extract every asset there is through these ggpack files there are a couple of extracted files (coming from Weird.ggpack4a through Weird.ggpack4f) ending with the *.bank extension that look like this.

![MasterBank.bank](https://files.catbox.moe/o0bzz7.png)
![MasterBank.assets.bank](https://files.catbox.moe/akzmb9.png)
![Music.bank](https://files.catbox.moe/v1gccc.png)
![Talkies_en.bank](https://files.catbox.moe/nlqnjb.png)

**Comment by JanFrederick00** [comment] 2022-09-27 05:04
The issue is that the fmod bank files, opposed to every other file type, are not xor-encrypted (presumably to help with streaming the data). 
Trying to decrypt them accidentally encrypts them.

**Comment by modusc896d352** [comment] 2022-09-27 15:04
yikes, that kinda sucks.
i really hope this gets fixed someday.

**Comment by fzipp** [comment] 2022-09-27 16:01
Fixed in v0.6.1.

**Closed as completed by fzipp** 2022-09-27 16:01 UTC

**Comment by modusc896d352** [comment] 2022-09-27 16:17
holy cow, you made it! now i won't have to deal with garbled bank files any longer!
